/* Generated by AN DISI Unibo */ 
package it.unibo.parkingmanagerservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkingmanagerservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
			lateinit var weightSensorActor : ActorBasic
			lateinit var outSonarActor : ActorBasic
			lateinit var thermometerActor : ActorBasic
		 	lateinit var fanActor : ActorBasic
			
			
			var SLOTNUM = 1
			var INDOORTOKEN  = "1" //tokenid dato al client
			
			var OUTDOORTOKEN = "1" //tokenid ricevuto dal client
			var CARSLOTNUM =  0
			
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						
								outSonarActor     = sysUtil.getActor("outsonar")!!
								weightSensorActor = sysUtil.getActor("weightsensor")!!
								thermometerActor = sysUtil.getActor("thermometer")!!
								fanActor = sysUtil.getActor("fan")!!
						println("Park System START | SERVICE")
						forward("startthermometer", "thermometer(V)" ,"thermometer" ) 
					}
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("ready") { //this:State
					action { //it:State
						println("waiting for client | SERVICE")
						delay(3000) 
						println("Trolley returning at HOME | SERVICE")
					}
					 transition(edgeName="t00",targetState="acceptout",cond=whenDispatch("pickup"))
					transition(edgeName="t01",targetState="acceptin",cond=whenRequest("reqenter"))
				}	 
				state("acceptin") { //this:State
					action { //it:State
						if(  	`it.unibo`.ParkManagerService_s2.ParkingSlotsKb.indoorFree &&
										`it.unibo`.ParkManagerService_s2.ParkingSlotsKb.checkSlots() > 0
										// TODO (next sprint): controllo sullo stato del Trolley
						 ){ SLOTNUM = `it.unibo`.ParkManagerService_s2.ParkingSlotsKb.findSlot()  
						updateResourceRep( "SLOTNUM"  
						)
						answer("reqenter", "slotsnum", "slotsnum($SLOTNUM)"   )  
						println("SLOTNUM = $SLOTNUM | SERVICE")
						updateResourceRep( "slotsnum : slotsnum ($SLOTNUM)"  
						)
						println("Trolley is moving to Indoor | SERVICE")
						}
						else
						 {if( checkMsgContent( Term.createTerm("reqenter(V)"), Term.createTerm("reqenter(V)"), 
						                         currentMsg.msgContent()) ) { //set msgArgList
						 		 var W = payloadArg(0)  
						 		request("reqenter", "reqenter($W)" ,"parkingmanagerservice" )  
						 }
						 }
					}
					 transition(edgeName="t02",targetState="carenter",cond=whenRequest("carenter"))
				}	 
				state("carenter") { //this:State
					action { //it:State
						 `it.unibo`.ParkManagerService_s2.ParkingSlotsKb.indoorFree = false  
						emit("carindoorarrival", "cia(car_arrived)" ) 
						 	INDOORTOKEN = `it.unibo`.ParkManagerService_s2.ParkingSlotsKb.generateToken(SLOTNUM)  
						answer("carenter", "receipt", "receipt($INDOORTOKEN)"   )  
						updateResourceRep( "receipt : receipt($INDOORTOKEN)"  
						)
						println("INDOOR TOKENID: $INDOORTOKEN")
					}
					 transition(edgeName="t03",targetState="moveToSlotIn",cond=whenEvent("weightsensor"))
				}	 
				state("moveToSlotIn") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("weight(W)"), Term.createTerm("weight(W)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												var peso = payloadArg(0)
												println("Weight: " + peso)
						}
						println("Trolley moves from INDOOR to slot $SLOTNUM | SERVICE")
						 `it.unibo`.ParkManagerService_s2.ParkingSlotsKb.indoorFree  = true  
						 `it.unibo`.ParkManagerService_s2.ParkingSlotsKb.setSlot(SLOTNUM, false)  
						stateTimer = TimerActor("timer_moveToSlotIn", 
							scope, context!!, "local_tout_parkingmanagerservice_moveToSlotIn", 3000.toLong() )
					}
					 transition(edgeName="t04",targetState="ready",cond=whenTimeout("local_tout_parkingmanagerservice_moveToSlotIn"))   
				}	 
				state("acceptout") { //this:State
					action { //it:State
						if(  	`it.unibo`.ParkManagerService_s2.ParkingSlotsKb.outdoorFree
									// TODO (next sprint): controllo sullo stato del Trolley
						 ){if( checkMsgContent( Term.createTerm("pickup(OUTDOORTOKEN)"), Term.createTerm("pickup(OUTDOORTOKEN)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  OUTDOORTOKEN = payloadArg(0).toString()  
						}
						 	CARSLOTNUM = `it.unibo`.ParkManagerService_s2.ParkingSlotsKb.checkToken(OUTDOORTOKEN)  
						}
						else
						 {if( checkMsgContent( Term.createTerm("pickup(OUTDOORTOKEN)"), Term.createTerm("pickup(V)"), 
						                         currentMsg.msgContent()) ) { //set msgArgList
						 		 var W = payloadArg(0)  
						 		forward("pickup", "pickup($W)" ,"parkingmanagerservice" ) 
						 }
						 }
					}
					 transition( edgeName="goto",targetState="picking", cond=doswitchGuarded({ CARSLOTNUM > 0  
					}) )
					transition( edgeName="goto",targetState="tokenError", cond=doswitchGuarded({! ( CARSLOTNUM > 0  
					) }) )
				}	 
				state("moveToSlotOut") { //this:State
					action { //it:State
						println("Trolley moves to slot $CARSLOTNUM | SERVICE")
					}
				}	 
				state("picking") { //this:State
					action { //it:State
						println("Trolley picking car from slot $CARSLOTNUM | SERVICE")
						delay(3000) 
						 `it.unibo`.ParkManagerService_s2.ParkingSlotsKb.setSlot(CARSLOTNUM, true)  
						println("Car is in Outdoor area | SERVICE")
						emit("caroutdoorarrival", "coa(car_outdoor)" ) 
						stateTimer = TimerActor("timer_picking", 
							scope, context!!, "local_tout_parkingmanagerservice_picking", 100.toLong() )
					}
					 transition(edgeName="t05",targetState="ready",cond=whenTimeout("local_tout_parkingmanagerservice_picking"))   
					transition(edgeName="t06",targetState="timeout",cond=whenEvent("timeout"))
				}	 
				state("tokenError") { //this:State
					action { //it:State
						println("Invalid insert Token!")
					}
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("timeout") { //this:State
					action { //it:State
						println("%%%% TIMEOUT %%%%")
						emit("alarm", "timeout(alarm)" ) 
					}
				}	 
			}
		}
}
